Create PULL_REQUEST_TEMPLATE.md
WeeverApps/kue pull request #2
Opened 2021-05-26 14:02 UTC by rgeraldporter

2021-05-26 14:04 UTC, DRadke826 approved these changes

2021-05-26 14:04 UTC, JenChampagne approved these changes

2021-05-26 14:08 UTC, AdamSutch approved these changes

2021-05-26 14:09 UTC, AdamSutch requested changes
Umm hold up, this is a public repo. Do we really want this template in that?

2021-05-27 18:15 UTC, rgeraldporter commented
> Umm hold up, this is a public repo. Do we really want this template in that?

Ah, true. Do we have a way to make an exception in Vanta for this?

2021-05-28 18:35 UTC, williambuttenham commented on .github/PULL_REQUEST_TEMPLATE.md
> +### JIRA Ticket Link
```suggestion

```

2021-05-28 18:36 UTC, williambuttenham commented on .github/PULL_REQUEST_TEMPLATE.md
> +### Other considerations
```suggestion
```

2021-05-28 18:36 UTC, williambuttenham commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Hours are logged in JIRA ticket (always required)
```suggestion
```

2021-05-28 18:37 UTC, williambuttenham commented
I think this could still work if we remove these fields?

2021-05-28 19:01 UTC, williambuttenham approved these changes

2021-06-02 13:56 UTC, williambuttenham approved these changes
Looks good!

2021-06-04 18:01 UTC, merged